import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ozan Batuhan Kurucu Portfolio</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <p className='mt-5 ml-2'>asdas</p>
      </main>
    </div>
  )
}
